### PR TITLE
Added new example

### PR DESCRIPTION
**Pull request by sceary-expert**
Added Example where we can use both promise and async, await.
Users will be able to understand how they can use both async - await and promises.

### CODE REVIEW

**Comment by sceary-expert** [comment]
@onecompiler-ops can you please review the changes?

**Comment by kshitijmishra27** [comment]
@onecompiler-ops

**Review by kshitijmishra27 — APPROVED** [review]
good work buddy 😄 good text good examples

**Comment by onecompiler-ops** [comment]
@sceary-expert Changes look good, added a few minor comments about the example. If you can fix it we will go ahead and merge

**Comment by sceary-expert** [comment]
@onecompiler-ops Can't see your comment bro!

**Review by sceary-expert — COMMENTED** [review]
Looks Good

**Comment by sceary-expert** [comment]
> @sceary-expert Changes look good, added a few minor comments about the example. If you can fix it we will go ahead and merge

You haven't commented yet!

**Comment by kshitijmishra27** [comment]
> > @sceary-expert Changes look good, added a few minor comments about the example. If you can fix it we will go ahead and merge
> 
> You haven't commented yet!

they mean is you have to add minor comments not long comments

**Comment by sceary-expert** [comment]
> > > @sceary-expert Changes look good, added a few minor comments about the example. If you can fix it we will go ahead and merge
> > 
> > 
> > You haven't commented yet!
> 
> they mean is you have to add minor comments not long comments

They are telling they have added some comments.
@onecompiler-ops can you clarify what did you mean?

**Comment by onecompiler-ops** [comment]
there was other comment about using India specific examples, please make them generic use $ instead

**Comment by sceary-expert** [comment]
@onecompiler-ops Let me know if it's alright now.

**Comment by sceary-expert** [comment]
@onecompiler-ops 

> @onecompiler-ops Let me know if it's alright now.

@onecompiler-ops

**Pull request merged**
